apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-app
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 13.13.1
    helm:
      releaseName: kube-prometheus-stack
      parameters:
        - name: grafana.enabled
          value: "false"
        - name: alertmanager.enabled
          value: "false"
        - name: kubeStateMetrics.enabled
          value: "false"
        - name: nodeExporter.enabled
          value: "false"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: orange
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
