apiVersion: v1
kind: Secret
metadata:
  name: gitops-poc-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/sekarfeb/gitops-argocd-poc.git
  password: TOKEN
  username: dummy
